apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system

helmCharts:
  - releaseName: rabbitmq
    namespace: rabbitmq-system
    name: rabbitmq-cluster-operator
    version: 3.2.10
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    includeCRDs: true
