apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

helmCharts:
  - releaseName: loki
    namespace: grafana
    name: loki-stack
    version: 2.5.0
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
