apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poketwo
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/oliver-ni/kube.git
        revision: main
        directories:
          - path: "*/*"
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/oliver-ni/kube.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ path[0] }}"
