apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/poketwo/kube-manifests.git
    targetRevision: HEAD
    path: argocd/argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
