apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poketwo
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/poketwo/kube-manifests.git
        revision: HEAD
        directories:
          - path: "*/*"
          - path: "argocd/*"
            exclude: true
  template:
    metadata:
      name: "{{path[0]}}-{{path.basename}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/poketwo/kube-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[0]}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
