apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-master-0
spec:
  storageClassName: openebs-hostpath-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
