architecture: standalone
usePassword: true

auth:
  existingSecret: redis-auth
  existingSecretPasswordKey: password

master:
  persistence:
    enabled: true
    size: 32Gi

metrics:
  enabled: true
