apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  loadBalancerIP: 204.16.243.195
  selector:
    app: minecraft-server
  ports:
    - port: 25565
