apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  selector:
    app: minecraft-server
  ports:
    - port: 25565
