apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  serviceName: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest
          resources:
            limits:
              cpu: 2
              memory: 16Gi
            requests:
              cpu: 2
              memory: 16Gi
          envFrom:
            - configMapRef:
                name: minecraft-server
          env:
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-server
                  key: rcon-password
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
