apiVersion: v1
kind: ConfigMap
metadata:
  name: ag-otter
  namespace: bmt
data:
  DJANGO_SETTINGS_MODULE: config.settings.prod
  DJANGO_DEBUG: "False"
  DJANGO_MEDIA_ROOT: /assets/media/
  DJANGO_STATIC_ROOT: /assets/static/
  DJANGO_ADMIN_URL: admin
  DJANGO_ADMIN_NAME: Oliver Ni
  DJANGO_ADMIN_EMAIL: oliver.ni@gmail.com
  DJANGO_SERVER_EMAIL: oliver.ni@gmail.com
  DJANGO_DEFAULT_FROM_EMAIL: oliver.ni@gmail.com
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,ag.poketwo.io
  EMAIL_URL: smtp+tls://atomicgrader@gmail.com:PASSWORDHERE@smtp.gmail.com:587
