apiVersion: apps/v1
kind: Deployment
metadata:
  name: ag-otter-worker
  namespace: bmt
spec:
  replicas: 8
  selector:
    matchLabels:
      app: ag-otter-worker
  template:
    metadata:
      labels:
        app: ag-otter-worker
    spec:
      containers:
        - name: otter
          image: ghcr.io/oliver-ni/ag-otter:latest
          command:
            - celery
          args:
            - -A
            - config
            - worker
            - -l
            - info
            - --concurrency
            - "1"
          resources:
            limits:
              memory: "8Gi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "10m"
          envFrom:
            - secretRef:
                name: ag-otter
            - configMapRef:
                name: ag-otter
          env:
            - name: C_FORCE_ROOT
              value: "true"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ag.bmt-ag.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ag.bmt-ag.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DJANGO_DATABASE_URL
              value: postgres://$(DB_USER):$(DB_PASS)@bmt-ag:5432/ag

            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: ag-rabbitmq-default-user
                  key: username
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: ag-rabbitmq-default-user
                  key: password
            - name: RABBITMQ_BROKER_URL
              value: amqp://$(RMQ_USER):$(RMQ_PASS)@ag-rabbitmq:5672/

          volumeMounts:
            - mountPath: /assets
              name: ag-assets

      volumes:
        - name: ag-assets
          persistentVolumeClaim:
            claimName: ag-assets
