apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-riks

helmCharts:
  - releaseName: vcluster-riks
    namespace: vcluster-riks
    name: vcluster
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesFile: values.yaml
