apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-proxy
  template:
    metadata:
      labels:
        app: http-proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: server
          image: ghcr.io/germanoeich/nirn-proxy:latest
          ports:
            - containerPort: 8080
            - containerPort: 9000
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
