apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal

helmCharts:
  - releaseName: keycloak
    namespace: internal
    name: keycloak
    version: 16.1.5
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml

resources:
  - postgresql.yaml
  - pvc.yaml
  - secret.yaml
