apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak
  namespace: internal
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
