auth:
  adminUser: admin
  existingSecret: keycloak-auth

production: true
proxy: edge
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 50Mi

initContainers:
  - name: download-resources
    image: alpine/git
    command:
      - /bin/sh
      - -c
    args:
      - >-
        mkdir -p /keycloak/providers /keycloak/themes/keywind && wget -nc -O
        /keycloak/providers/keycloak-discord-0.4.0.jar
        https://github.com/wadahiro/keycloak-discord/releases/download/v0.4.1/keycloak-discord-0.4.1.jar
        && (git -C /keycloak/themes/keywind pull || git clone
        https://github.com/lukin/keywind /keycloak/themes/keywind)
    volumeMounts:
      - name: keycloak
        mountPath: /keycloak

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hostname: auth.poketwo.io
  tls:
    - hosts:
        - auth.poketwo.io
      secretName: keycloak-ingress-tls

metrics:
  enabled: true

externalDatabase:
  host: poketwo-keycloak
  port: 5432
  user: keycloak
  database: keycloak
  existingSecret: keycloak.poketwo-keycloak.credentials.postgresql.acid.zalan.do
  existingSecretPasswordKey: password

postgresql:
  enabled: false

extraVolumes:
  - name: keycloak
    persistentVolumeClaim:
      claimName: keycloak

extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/providers/keycloak-discord-0.4.0.jar
    name: keycloak
    subPath: providers/keycloak-discord-0.4.0.jar
  - mountPath: /opt/bitnami/keycloak/themes/keywind
    name: keycloak
    subPath: themes/keywind/theme/keywind

extraEnvVars:
  - name: KC_HOSTNAME_URL
    value: https://auth.poketwo.io
  - name: KC_ADMIN_HOSTNAME_URL
    value: https://auth.poketwo.io
