apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal

helmCharts:
  - releaseName: retool
    name: retool
    version: 4.11.6
    repo: https://charts.retool.com
    valuesFile: values.yaml

  - releaseName: retool-postgres
    name: postgresql
    version: 11.9.2
    repo: https://charts.bitnami.com/bitnami
    valuesFile: postgres-values.yaml
