apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal

helmCharts:
  - releaseName: retool
    namespace: internal
    name: retool
    version: 4.11.8
    repo: https://charts.retool.com
    valuesFile: values.yaml

resources:
  - postgresql.yaml
  - secret.yaml
