image:
  repository: tryretool/backend
  tag: 3.10.2

config:
  licenseKeySecretName: retool-auth
  useInsecureCookies: false
  auth:
    google:
      clientId: 997504863600-6nfvs9g5cbtovgnfjpq50h6r3p7jnr2l.apps.googleusercontent.com
      clientSecretSecretName: retool-auth
      domain: poketwo.net
  encryptionKeySecretName: retool-auth
  jwtSecretSecretName: retool-auth
  postgresql:
    host: poketwo-retool
    port: 5432
    db: retool
    user: retool
    ssl_enabled: true
    passwordSecretName: retool.poketwo-retool.credentials.postgresql.acid.zalan.do
    passwordSecretKey: password

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: retool.poketwo.io
      paths:
        - path: /
  tls:
    - hosts:
        - retool.poketwo.io
      secretName: retool-ingress-tls

postgresql:
  enabled: false

persistentVolumeClaim:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: rook-ceph-block-retain

env:
  DEFAULT_GROUP_FOR_DOMAINS: poketwo.net -> all-users
