image:
  repository: tryretool/backend
  tag: 2.117.5

config:
  licenseKeySecretName: retool-auth
  useInsecureCookies: false
  auth:
    google:
      clientId: 997504863600-6nfvs9g5cbtovgnfjpq50h6r3p7jnr2l.apps.googleusercontent.com
      clientSecretSecretName: retool-auth
      domain: poketwo.net
  encryptionKeySecretName: retool-auth
  jwtSecretSecretName: retool-auth
  postgresql:
    host: poketwo-retool
    port: 5432
    db: retool
    user: retool
    ssl_enabled: true
    passwordSecretName: retool.poketwo-retool.credentials.postgresql.acid.zalan.do
    passwordSecretKey: password

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: retool.poketwo.io
      paths:
        - path: /

postgresql:
  enabled: false

persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: rook-ceph-block-retain

env:
  DEFAULT_GROUP_FOR_DOMAINS: poketwo.net -> all-users
