apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal

helmCharts:
  - releaseName: outline-redis
    namespace: internal
    name: redis
    version: 17.4.1
    repo: https://charts.bitnami.com/bitnami
    valuesFile: redis-values.yaml

resources:
  - redis-secret.yaml
  - postgresql.yaml
  - secret.yaml
  - obc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
