apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbl-auth
  namespace: poketwo
spec:
  encryptedData:
    dbl-secret: AgAJYWPLayu4fCaoVBP2f8mEgUbupx2QVJgGnLU35sbAX1y3cIBRlR/BfrAXadnGoHf7ph1asnbK3KtN9T8ycUpA1BFCjoHOgtfM99dkP/0A1znkZr3hc/8io2uQ1jMAMzJCxWa01xp98jU3fToxFQ5DZii/Y223ZKTnwID1YZmg9zrQxcHTJfO0tZziu57Vvurw1vWpc4D04S//29F/RUos20jiPfmhUT+i3l3RnB/H3cHAoi2XWOlRaZXQja1oZ9Ec3vfxlEVf6uxRwDzi6Ds80Y/xiT7u3qsILdmCBlPZFwE6AYvifOObcplS4CbSw00gdl3dDoYKScU2ZLDbhEJosDpuesdTF7URU6abA9+dIE2QyvXpyjIck7+KRM6xhFawQ2NcotGsQBAOPJLdWH4//Oll0bB/4uEjWdY5TEFaHAvpPziQblvW6J9HL95BmZaKfEcHa/rew+Y98aN0kIhDv82VMFPTZJ6tPex9eTfNlshpkRipsCuPO4w7+RGzrC+F0S79+VBosJAe70pxBPArFnrONFFfyOCWbbLqXaMZiSJQgTm1aEW6nReyiihmWZsH8xBFbMpmlKEAt04mvnTXALZhC3uTi/BWd6kgEHQ8r845QnN9e7SH05pUXkPd5mtzqwgo5E6AiOy3DciJF+NqSWHclb/tDUcYZVxXiXQxJhSLukUZ4NfwD2GO+bXdt6WigIawkzlGAO7IxBF3YdSCtGZ9AexPiYDpWzrjqzzDLQ==
    dbl-token: AgAiSjKIO0elqvaYyRgJWxt5yenOu2MGsxuY+FrkBARqfUbHc/COBv2S7cxshZO+5sTqzp+7CIUHo77j+EHSTm7xLtQaaSXR+msO2+dj4sS1fU00RW0p/TkK+9vF4HJ27G5nKg+OyC8zkuDeJHAtu8+S6JBYbVyVEzHSyXo91ndWoxYBYmhLZGx0457fptl4aJOgRCy9XUuPpNPb6HO2ZPXsfq/7OwcY1n66xQPTWMp5iqmuawtKjssFRrWtAJwRmLtzfEgnG2Mo5vZbr039hYubRUmclWswrjlw9CBYOpEveiUi9P7RNBRwjo3llc5PjGdUzveopGQBTJKHhwyYtlGez/4ywaP4GRRnZlTtW1hu6yIWdKz45Jg5Hldt+B4BTnCurV0lVC+Qgsv1nQieJseUheHX8oG9oRxf2/681haMknqNBZhlYG9qu+BFS9Ho+Jn86U/cJVYjy5XKZj+rUA2FeWWLOh/9Ne1euI6JJZ+Ixu4uzbh86uGmCYSG0Y0gxFuqrImZSVeqKAIU22OhimfUZr8m6Jo3lhOJbdbng4K6N5JOggGKWeqEVN1qBm8S987GKBWXtm6d4+xqPiUP1MnRdc/sC+igkxngfKKrBO6QQMj5NUls+2xQjmaEP+gQKiTsbYIyMSzJRq6qAZTFhU5QfcrKmwXelBiW3V849fh7tbqOCYvv4pfEZQSBhtJvNP01B84DQkiWu+T2g0Nfle+xb4B6HPsTNzQhYguLwFPre2RiUAFplZZ02kFE2/0qWy4Ewr3i9v6leF5/n/Wyf5cUehgXp4jOv/k3jwwz6ER3zsAeFS+y76C/l//pXHq1rtX7B6xhneUgETnsRzNHhXWyx4fpI2m3Yzj+Kj1VJfyjef4DtbD2WydE28Wj7vOt2j2TuvRNpXPuNsMzKg==
  template:
    metadata:
      creationTimestamp: null
      name: dbl-auth
      namespace: poketwo
    type: Opaque
