apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-auth
  namespace: poketwo
spec:
  encryptedData:
    .dockerconfigjson: AgBqOk0a3G7k93Dn9XbaqAVDjFQEz74EwEZhXa61Zo7FriaFv5xLGS9IhoTO1YQx9xzv9/CMREFyu3yOi5BuNuYbCdoD1HhuBl3w5D0YDqd37Zq4+MzV7KeL6zTp4errc2QBouV0lOuDFlZBxKLmdoADuuJ7gGtrSeYNJlUWu6nbAOFrE/TPYRvglWHRZ++mdw9Qf11GYZDuIwASa2dNjH1fzOzUBhSTWUe9O/GX4BI+qT6X0bhDa4DjPVo6OcOztELJ2/MKZ8sQ1gcE51NvP87iC5tQKjaRH+waxWsduNUaViAlzPIU/iCVFoSw4Vi5f3u7V+ljfJao0BGFh7El3MLyj9sBxnqXWwsSlVKlNBzoBwTmsBtYz6+B5qoiUSb4ANtDPJQxoAd8KG0YIK9Wb83JgmxVlMQ+QJlIs3VTUcD+HAPqf4EF6wCOtnQufSygR7MAIzc6mahhdMKqDS3fxJENRTGqSpde1gZm+cYUx+O3KWbSNnut6B4Tmx+16l+FEJMWzwJgO6Glh8wLLroSPZjQTWpZhGfOmWtG4LPPvvsVUfjy6mkXpCiLf/H0u9BQl+45RMhdAY5WpjrNt9c+ZuP/wnblclK880Xfbg2yW00KInf1gpC5LPcX/6W0Rg8l4YgDJXHWlYh+LFNEFbo7PqbYkqAtDhYV+zSrWslHLwIiXLZeRN+Z1a3QPW3IiA5idpxPgtMDMv/PhhT0pOXpT4zDOCiVeWf6mzCiWQDQzUxc9CTspbxo7/DqSGQpAhUczPofwKQirXhxfG5NLLFalhQIIShWF7ScZebnf6ij8C+qQHHukSocCvfQKtuUmkkNslEEXIAzrw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-auth
      namespace: poketwo
    type: kubernetes.io/dockerconfigjson
