apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
spec:
  encryptedData:
    grafana-api-key: AgCI28bp+LulJTAU3mpjc8YI3ciOnsCjN1i1rSN0GMnncO+TNNWAtpxuiY9ff7QS44uR/9N9O/GYkcR7r+1dOKBJiuEB3LgyzvYSbMhMvazhoh/jJb/3Stwjms5Bk4zIdjtat7TXOWIuAqcauu+SDoWOukrjD5WGx2aQAXHAvyBuI+wWuP0sTnZwB5s5yGWXD1HQv31u4MT0s44ghAG194ktLpaNFJWbD6cSatn4uiNXK0bi3rM9KPPP7sEFiOf1cUh8AoVaTA1trll5wka1EqYW+HHnWtTIn6QNDkkXiaemjAMR7fw9G2/taNh0PoSwQHwPn3cj6gVuks9hDNzNqxw7g5RdCS5SM6XihXDY/1OvOe3cq3jFEAFKUelgE61JjfAGOHYLnNetv3mfMqn2G2C991KDLs9Iyj4bcgu10oYH3ZbsICP+a8bNycEeQZsQ4s90HXNNaJlr363+5lBksN7RhmP3li5sDkguWYYNcFqUI2zxbuFiJ7qTH3x0a3lq1Aoy43BWfXXk80z4Y4nT0HkjJ3ziCpZVNXN9iiE9VWmzwiO931N/t9XhrovAC8GClDF1jbkJMouc7R1hohtwM2aBVaFqZVxcyQ04Wt+S4BDtDZZCILdDQWFAT5QksCMDhn6J1lAUu+5YhfrY5RNZVuDGaZVOXIHv1MO+LMxf/vmhB4Yhv0aCQP1+Mb1kxEt+8qI6c2mtwiyJ19V9UbhinArhp8ACCUVP0pMvHmgoyKBtAUr+j4nfWBRGzCVGXryyxAg/kuyphAeUeyWWWzwyHLtUxc22IabXIcAs2fhFjSK++Gbc+1qceDFSwdoqlHnQlUaJsyKrwdJCL/e2E9U=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
