apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.4.14

resources:
  - ingress.yaml
  - argocd-notifications-secret.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-notifications-cm.yaml
  - patches/argocd-notifications-secret.yaml
