apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-public-1
spec:
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
