apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-public-auth
  namespace: poketwo
spec:
  encryptedData:
    mongodb-replica-set-key: AgB7yb9XTPo80D1NB9qDnRtLE3wweX81BTjfdWFfnlIoYIcSUGe7GstJlcv/0ATRo5EEMgGySeLqYKbPszoASd1ZxKrKm4kMiHxFZnzOLsLMKiGb2vXTBKAnoKcaQa3BhuuRwMwyk0jf/qu8wUuiwO8MjCakoIhFrIJM785JXDQiIF6NSmFqwZYNoYTIS/SS0CX0eahR5i54qSCjo7nXbc8Bq9KSBVxfJHsDTsYAfCxjkoY2E6AgUA6Ke1RVVQxzaDu9CKZJ7nbaFEc4S/ODOfVL7KTHIwrihSJOdAU2ukuj+SLER/wXzPOftYCWxyt0foM4TA8NOW40ADxuPOOS+Sm4m8MrsNPRJk4gDlzP/LKS6cRI9hV5QdHbqPPIvDgq4dSOOfTpToF5GI/1EhzU7cGXnTeSOJzTyL8qYr2dyMtrIporzHmk+IdNobLgVzDEyG+DAVDw+xgfbeFa/ug2EGRlyKJkquD10iDc+QcS5xhbcRsfhWPCZBp/pNWlS2WhPAt0oNYMPID5LoCzm9dnEy2xwjuPOjU6MVE43k2axHFv9pPKsxVePM+ZkFc+K10BIwwh3ECM1f9qqBvAhhOmeX9O1CgC62S5g5s5hFPLHPimUozr/f/daVSWcCXH1ohPfgAIsKbJnb6CaVy5FJSGzdTHtlbBIF6YoAR0YTRiHv9KZmQ489Cht2Pl1A6FmUB1grVgbjW+Yq4cFDdxiAdZVIFXPdr5BCt6SkzWdF6qXflwyw==
    mongodb-root-password: AgBhsmUJSdezoSNFgY/KzARxF5fvKuZ4NukgRQwUm9plUSUh30YXERYX59FW1+RxQJilrpghbORbPLpXPOFUkaQws80y1rb9dh0QfX53IlPnE24jj+RvmEXRm/aV3YH1ovdWAkYZ2E3pkoxiNepRznvbm2jZ1j6t8be3FbtIlgUpz9l0qK2v3CU5SRG72gEvJdMl9jzM/hb7qC/B4cQTwoCs7RzRfzrDdyTsqhbd4ZINTJTCoIvJJ0XQihrc/lXaQXj8amG9Uqe2JEzO5MhQ7B9KOgJR58R2VPVptO5zEx9z2mqIPFHzx8ZuEZgEUlHxKkFR5NelZFlyn4oq2lk6TASD+ZZR2dKCFPDGDVxEWxKl8ICPwReAc3WUO60p5birSuQEQuwSeE1Zwhu/JEH+dfPilYRogjVDTWyvKGF2MivCQ4PgwOl6SZzeQF3DqMPpJFFnkzi34iDjEu3tLcUMjRVN3u+Yz42HQIHQH1jeaYI7IG+5ZdGdhyJ0QjQkIt3LAIDF5XNICcg8uiPtNIzPg5AJIfXgR+ZiB7c9jFlnf2UemqQDKBt4I3bSYeRuvdlHmC1KqZ6/31YrIJxVDXYH0hJddBaFisltNphsRkQbVfZkXcIpqO2ceMJS+to2gQvAvZ4GoiV7hyAOcHBwgXLGj/CjqYOjKYjfPkxDrWQWxd3mYvUiIY9B6+jn77clR8IKRizaFQ2eIr+1ltaIdh0AjVdotx/tgjANJye+4Md1tYahyh3ASsjIjEGRH+SEbKKA3nGULogrP3cvlOA6t/T4VuVS
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-public-auth
      namespace: poketwo
    type: Opaque
