apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

helmCharts:
  - releaseName: rook-ceph
    namespace: rook-ceph
    name: rook-ceph
    version: 1.10.7
    repo: https://charts.rook.io/release
    valuesFile: values.yaml

resources:
  - cephcluster.yaml
  - cephblockpool.yaml
  - storageclass-1.yaml
  - storageclass-2.yaml
