apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: --enable-helm
  resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition:
    |
    jqPathExpressions:
      - ".spec.conversion.webhook.clientConfig.caBundle"
