apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration:
    |
    jqPathExpressions:
      - ".webhooks[].clientConfig.caBundle"
  resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition:
    |
    jqPathExpressions:
      - ".spec.conversion.webhook.clientConfig.caBundle"
