apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: guiduck
  namespace: poketwo
spec:
  encryptedData:
    outline_api_token: AgBZVk1kfEmHN+wvoavkitpeZAXUnD5okV23PscdzJnMSoTxXznwejBgl2uShepCtx7DGMQJKmIz9+IoNnvBSglkB9LVNuEjyXlcaoIgZsMt44VYCpaPWyPNUjB5qRuJQbrY0eXA/Tz10IFfTpFx/ATsUdJnfcjf2WorIwGiBkqAIt04vQv+OUeqiT57WVD6RT67pSQamObVTM/4tdhDaE2iTJOyL0KuWm1Ex98xv+9b6Rsui9+asiPv0Ktim0pfUtS7t1pbWpE0w2jDn0rREx18bg6Azm5rlbQFtTLgqbvyrI9NRshjxwQNkfuyRxttfJ+7EP+bHBG33Utp8M6E3V0SG+1mIwmnNnPfeaHCXDEzQD5bVCKUoMB2WGMLZmdYzYTDvJ8TZCh0sYNi481rOXc2lvD30Wsm0UKk0hAzE/aKDaR+hKknXBrn7WXYXydiKY5Ha9s7oEc7croRqAlGaqPZSo7/CWDpijxZxzCp+Frt7tXi5QsQXMwvkNvZ/Alp/6jsVx6GjJUcpphoyqaZu9yM0DdedQ7nCwyuXM2wWKXQAzNv2fx6JTiMB2Ev1RxwilJ8wIB8QJ28BZXhkJsSiAe6YFqQFlBLfNtU8jFCiK3tOJslDZ7kKRMNAfcD9yPI95JvRN9F9hKFa6upKJuZxOWOzF7XnSb9AufLOBW0ehCxJR8S5hTYEQ1R75I7xpPOVQKuZefRRWfNV7Mtil4llQXUQ0D1A4m/pzNxfxRS8IJI8C6gTXc0/dAjh9EBQys=
    token: AgANf8nfMNjlYGKNd6P4jnHRGC+7KuABQ9J3yKoSoSRIQFKSqEHb/kHScE+aIplCgSsIMfs3cs88/+7+DVxL5jgoinpHAvuiJXLkNvnQvar0cBW5rZF6l5ths4ajAGUS1BKOFJMxwo603DFVxwFEIMxS93gxT4DRSXrzNN4D7cZelZVjwJ5enTzMwMEfGxmIsiEpSPiyR5c/SrlYOuJGytg+v8tXfJpjIF0/H+sZyx00wSZsiqwgjNsYAJYCcuasb8+N8Cbbd+dDg1dgwoOfNYBVJmz2syrmuWLrTtohzSaS7VbVja/mOtHOFUMMnbWyxDyR9UmgegR04Y1UNFT0d/d1s7WCA/HA98DbLde1BAGv+EVqO0nqYYM8ElGIMVz37tfLb9IF1RiNuhXfZIaDB1GzfzRVraUc23gDe2vMww8pFmDlwX0PvHJaTR12lmzMq6PF1A+ZuDej4pUXGJpIRhlVGe31yC118JwClhlBSAbvPJJ84kPkbeGJ2aeMz3XIo6ah5xXrpdxYW03XkpLHB3BqCam6eUELmpkMwC2BF9QYlgFRg4VfXB6fVX2iu+fcPu3hSdG+8NzX29uj3ncXdnNRVlKVa79SZT6LCRbiiuOwnptScQnDLematWsaNJANR6g/o49ETXCrS6tGlleUMqsqGNv2qjsZsuXNTGW/o7F3bagnU1+vPLUzh6/zjPwHxrcpQpBwblmkzKhggrX+7NmmBYE614unBgKqaabu67PUEQZ1LG3Y6xBV4VqFjYMIGh1zpuKyEhMLH3SmGnaXswWQBPGqifWb
  template:
    metadata:
      creationTimestamp: null
      name: guiduck
      namespace: poketwo
    type: Opaque
