apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCSxwKruawPgsSr4m4o1NFIWxGoMGS6pSBURn5ZG0NnqyTPV1z3iDYY0Fa8u4RfeGd8l+BOCK0jGMjzLP/NTFfPPGm35OWJ7RrzbzR30P4ya0W/5GdIGtBpV44e5p+rOsicAb+DowkRLLUSxYWGhb8hBkxJTtf/NlDbL7v2fiMNs3ZH57sPxb5MHaKdZKrvpT49PdXRV30sd1sMD0iaoVsgYlsyuaN0Q3euC6vCU+9oaOwqmc0KtlK47hSEKi5PfpT/AkPoqMaUCUpqlax3T6dVE6rDL8ffv5usBawEq/Gm4KUbGV1A7kTuXjVA42Kf4rOqzV8Y7sdQsditszXxI+DCEEF8WEa8NaxpqRwXCnoQpm9gvYDMBoKGxfw1jl8uZYyjoL7dfXezDIR+1oQcnMFBUgxIehRflLqYCNRCAyszp/Ymm9/jg89rzDxXKntdrIFlMvz5+mW8wGnbtOnQ1cWAd2UTCu7tGKI2nxKLE1nP4N14hhuCmJWfhJq6JGgOBvAqbx8n7+rRJ+UUSdEo2yjWwIpGEHtQ9dkn3NzTwTeGS/mdDDSK5r7y/uJgeA5NA0sPbEYAc12kZ1VeJjyzRD92bFrDiZFMXxG9nZa5hQ59mM+fUDpNbmHOVwSShLNaVXP6/D1NXF6TysRgoCopM3mMIW834EQHdVN+x715sivFlsLi5cuj6H/NwEfET9H52gnjjbVa+hS7PhMZ
    admin-user: AgB9LrRCq2j31CY0P15e6dd9nDIZo4b1SGQLvKY86Fn0DV5se7ihuhygDqP0ZdW8kvsr6XTigQXSgSh8VzJQlhAradezFvCBJuy9V+k5fVcNZhdH+0Ro/OSTYFihoL9ZgbPB+wI4wNZidT7rxmw9+07M/n2ab1Ajg4KnYjYOL/nqPbJnQM/yZR7SMYwzU7HvjRXY9h2aHqJSspDXJtBFRwRjI2GkZziyt3SnzCaerU577za2Spw6xTKpTZqdQxFrQ2Py+0AF0YG0nl3k4iBLDd+KsJOUgstMcI74uYrM3P+HcXZJ78w2/6x3PSJpZtsqcu2KiTREGi2pYWsVST5oZ7Cg5McDq14mijkru50uuv7Ty3mZ0kSASZ3Hx2uCVWpblwsmU0EUe/RiabhRnwFNmCFCWSSVhC3l17dKLaC2ZlkuEf/iUDm32oIvXTDzZ4xf+OIf8HT6rwRm5umaHqG6ZflZIOutQZKAPl7EaeR1G7EjzL3DXwC77+mMr/UYLZrdPxS41+slY9f0DGUOW2CSu7QqnYy0TF1bxdgBye86elhvHnMoAXPF785JbooS4/+upZNoHv98GKsOWevSe5ZIkG7jyqxDVTq02xSWQUIjfjYLkRmFxwYRs+09hU8SP4K9g0LfQdq85HnVozXQ7Cf11DnLrfIYt7ImdjMSuqEVLB/VG8bUbFHRmfkb0bgFmyEk8uviRTzCnUs=
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: grafana
    type: Opaque

