apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCEJknJzba9VHNv/8IK8eMzhwlTgE546HBlY7sSg8dzUV1QNn0/XA/71+TlWU6Qz7ETkBPh7XCv1sp3RGyH76lvpBdseWz3B4lA8oibLBK4bcvm1c5ZdTn6uNscVsaXX8ph0jkeD+RP6k5vsXWeAbh2DPHa99w8CG3rp0vbqMYOw69p2mtxxyix6IwGgWYnovRVL9a8ltuxFXUIOHMnC1TfOZvqU8U17RGxFUGGT1N32Z56QRAoAkj973bCm0wrba1Hj3To64szSoMblK7J9E9pFBoFCUlOPw4SlVbbZKzL/JnZyUO0qiIFYSYHUcZQEEjAD/NTG3DcZLZH3amQws/F7Pht+DZtn5uAnOFE/KeFZKMPhcLnuuQsd9uaSGZyitPppLJgvtNFrrvFfhea62jYmEBwz1a6dTyf22OLK88kvCLl6jRBSybtMe063XjqP2ymOl7YRAF8CUjRpYs7X9Mo7kuLl6exanJgtQ7KXX5UTyijIXNmLglAOcjzLuceaFRclTD0mOPmnMxw0QwUcJaa6noTHY7rZG/LdHhF3/Uz5csyrK4qOB66aFNAVcKjk/SO5R9100AfZoGAxpex+o/T2/e7ef4Hp7C5B8W71oLj3zBQeQgCZ3ghkNzTlpP1czDZxNGbfJi3hLSle5jwDPkOCOnERIFlfc4ZILA00tKRSX/EW7zrzJSi+s7Y0MlZDhBZEsYLwcA=
    admin-user: AgARgZzuygkyM4xamNio1zykLgMCbSO/ImK0qjSzZfaHUD9aFX/d0uiYYzTG6Saw7QOWz17c6DIIZX4Rb4m2nQJYydErYrKQ0Rk2pOzBfEDhaM7xFAoQYsEyJWJJYY2eSsrma7yfmWNCvW1k162NYlpkNOdxNoAUQDlOvhuyWqH8RK4uuStK21FHBf1zJKVhazA7aluXNQD4/wmTXkjfm6EeGYXbhQ/dUEkp8rEHyIdwGfjQD18TWmrBZN4BDMeWsyRWhpPe5aZtEwjWxgvipAmMtYRw6cbFZGjlonw9XHFRQaUEs4Rz26qM2F6hysgc0Tpvl/yhy4BJBNOAVcqOTwz5bLcimgHBAKbKa5XczN16QwvmheTE6/ZxCJTkb0IBsEYpF6qU7ja1XcKo1yPHLDgNC6+F07KR5wA8knYKcswudHtFghD5GhJgEGKsLUDL2IVtz8cbwfJ17Sb9+u2zh/8Wk5h7CYLbcLKHd6s2yNdOEqX+ctd+vwwXkVGjDHCSN0pIlgMcuteSie1TcjW8kyqxkH/RFDKuLHKX62pY53PzHNj2gAR+Gn+NjJhqJcw3XQVksp9qdTgGw7EqEeXlq4W2Q56NxYcQodDn+4ColBJXPwVejidya/W8HOpTuzfhb2JSzriBWymkn/tfO48/h+4UR8fss/KI4FTwrRPoAfB4Co16OSX4/xkXUcb6FJ88IyF+qMmfXeUYXfwmInYnxKcfCGos/nfrDo7n4VkOgBooBg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: grafana
    type: Opaque
