admin:
  existingSecret: grafana

persistence:
  enabled: true
  size: 32Gi

grafana.ini:
  server:
    domain: metrics.poketwo.io
    root_url: "https://metrics.poketwo.io/"
  rendering:
    server_url: http://localhost:8081/render
    callback_url: http://localhost:3000/
  unified_alerting.screenshots:
    capture: true

extraContainers: |
  - name: renderer
    image: grafana/grafana-image-renderer:master-cea4f8c
