apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: poketwo-permission
spec:
  vhost: /
  userReference:
    name: poketwo
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
