apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poketwo-staging

helmCharts:
  - releaseName: redis
    namespace: poketwo-staging
    name: redis
    version: 16.12.2
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml

resources:
  - secret.yaml
