apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: poketwo-staging
spec:
  encryptedData:
    password: AgCFWFNqKM7CTdStbsEv32pQgT8XMlvfSGM+MX4FXPJgL6VjlRl2o0aiW+Wn5diLUdIPpyJkbK+cbSG/0NTjVmJau+wjV8eEdj8aOW32qxjwW2pCpVzdEhveXzAFAeNcz02JozgUn6QB8hZiEpIxeOOOQRqeC07EzGBKygMNaa8qAwi4dr7SLArpQYY7FeJJBTJrRVKMfimN7WheZVlyKTlr6V6wlyvN/nmVxqLt6fy3f/SNE8PfS6xVBmiAajAV0FghoBpw4MeALUFt9TAH+pPh9VZR1EZL4vwiBiFNdomabAB9kFUbr9I61IrcPpVS/qCyALBdryjwTtieQpVq/AcWWgiPndYCNFGyJnDfwsL+VxU3KA39mnqtUE+X1RjSIowzd/HwcYR7eaRfi4tTfJXUnQZezQgS5OJli8K+0f/WuNIdQc0CxogI+8DyiZQ8b44+3aAWl2/xzeQTwUhc8tO+zC3wDjWe4ftZmBWCwi55l7F7x00LLjseuIjdechDW+4egQizXAJd1cbiie8m9PeogMLWg/r1MfR3Wx8tS2tUkPTuGWt/Zdf3v2Cl6GWO8KnkhysOf7/TnGHhp5+16nBTs2Udn8aBtSqbuxJcc7J/26tzcq4pRdan6dlsZf4h6v2ry57Uf+MAzbSz5xFPhTK8lkjB40QUamH9CTu09nQGQALZsxW7yixatqs90EsIwRCCwF6vL/doZejYD3mqWnpiwoEYKiOUjjgWmT5YEuMhSA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: poketwo-staging
    type: Opaque
