apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-auth
  namespace: poketwo-next
spec:
  encryptedData:
    .dockerconfigjson: AgAfgNRZVrcaXIt3QE3QFQgGLUUZStEnCrOqOzUXinN6lbORC3EoFZ4expOwcJ6csqgW4/cQ4NSUEJywKW7pO5QlEGqWfkiou9amkv6iox8aoKpFJv8XvOr1otfJdz+F0Vosg+fdbwL/+kF7G5xB/yYJkKwOHV9Ca9TQ0XZ8B//JoDJ7bVRVJyNZdlEobhWqDLkNKMqAK5BuJHfBMBFQNDJYHYeX6KQO8Rg4cnZNIm5s/NeH/eCp2LdSVitBXf6nF0iSc4b0oppsKIrN3LmycJNV2rJouQgpc7EYfABm3K0Gz/g4v1rccTsjqJdYC0R27gDq8/zIAb70dvbAQGZdjddjomJCLLjDL6+NV118sAt/uQFR0vhGm4Kt1XAZK1Tf6KdrxsrVmbChbTUyuwi8JrH4dbjdU1k87QGfAv1/sFDbgONAN86I92QvPCOA6FL2P4yQDZf8UNZAjcHuY2Jb/LOYGR0luNWjU6mx55EGvJxSVHeYzt+4kB4qAt4xKI9NERRYJvt8emBLwne1rCgrw5DiLUFwI0nmz0N7uKRrEhxB4MbaXoXt5EUq7HiKdSdjrjCKhScq5UlYJGvFuL9hUU0IAbalfav10PtLeX+m+tLt+1pxTXauYPKEvqQcxyYIaBPW+bZU6Yoi4GTxOHdXlJ+Ks2/RjqjyB3bqdKrkUwXRqNrRf7WTL8yPZcFGK6oHcIOLekvXpW2kmmSUhuKImncDW6242JIn7HOwOq20ci9pIRxOCJdw3u5GXo6Q/gAx2qBaip0epdW4I58Xgqj5qzTvB+LjCyk8vqU1l5hAiisiq27I4jTI5g48bgKkt5ltkZyuOJa1bgP6dxytQwdyMAavZjgz0rihl7/VyAOMAl9hfU1422xYri1reUgwSFch3l6U5tEFF5n3Wrrc32CzTA5ZdlvVJWQKxOtJotNw
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-auth
      namespace: poketwo-next
    type: kubernetes.io/dockerconfigjson
