apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: one
  namespace: metallb-system
spec:
  myASN: 4200000003
  peerASN: 64535
  peerAddress: 204.16.245.193
  nodeSelectors:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - abra.poketwo.io
            - blissey.poketwo.io
            - corsola.poketwo.io
