apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

helmCharts:
  - releaseName: metallb
    namespace: metallb-system
    name: metallb
    version: 0.13.10
    repo: https://metallb.github.io/metallb

resources:
  - addresspool.yaml
  - bgpadvertisement.yaml
  - bgppeer-1.yaml
  - bgppeer-2.yaml
