apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

helmCharts:
  - releaseName: metallb
    name: metallb
    version: 0.13.4
    repo: https://metallb.github.io/metallb
    valuesFile: values.yaml

resources:
  - addresspool.yaml
  - bgpadvertisement.yaml
  - bgppeer-1.yaml
  - bgppeer-2.yaml
