apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poketwo

helmCharts:
  - releaseName: redis
    namespace: poketwo
    name: redis
    version: 16.12.2
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml

resources:
  - pvc.yaml
  - secret.yaml

patchesStrategicMerge:
  - patches/redis-master.yaml
