image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.0.2-debian-11-r1

architecture: standalone

usePassword: true

auth:
  existingSecret: redis-auth
  existingSecretPasswordKey: password

master:
  persistence:
    enabled: true
    size: 32Gi

metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
