apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

helmCharts:
  - releaseName: prometheus
    namespace: grafana
    name: prometheus
    version: 15.0.1
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yaml
