apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: metabase.poketwo.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
