apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-proxy
  namespace: poketwo
spec:
  encryptedData:
    config.json: AgBv2D80umgq+nhrXOQnHJyTFuTtL7nj5HBXY8N7OWe+eDAwAXlzmWNyZ5EPasWmMDQxwo34dDnkRZRrdaAiGDAkGlR/zr4X6askZ5gb3tBKkunKZjlLdAde8fBVcIRaRBNuWqK18wKmxrRUDgK+WAXX0ctBHu1TgRa35jAF8MqkQarHY0IHALcMZ1kQodY0LkPbSj1Wd8jInt1woC3eK9ebv/Oq3zeT/GjYl3i502tsYoi0s6Zu6/QIRwAxQxTXkMSULNv0XGiJjx5SBTu4MHULQjKmbYGeSzinAzzBNnzDssnS39dWzJPJjvT9seLc5FqnBdCIL4+8vOVc+2giDJZYWzMH43X8hpoSNmzJxCNWTKfBNkFi6PYSTfERYY7ZaKxVTE4iTL2P6J5bGV5uoUuFCz5RZYP3ofrwCj3eLlPwugW9D2XE+ZNa06RenSi4mVofECalvCOJIRFgtIhR0ZazB4ORSRgv9mFuZ5MWwsrldxA0kp9W7IzooSiau1PVnhfc57DGaimW90ZV7ULxquYwtcR5+fGt6QoLkCMOLcq/lmHnmPswvYRKnBqbOF+SZeuBWgAyAbWqlpbda97U6oLlmZAWyTvtVcdKpm4uObWNkahJ/7L6NsUrVHwCpAQr9JKcut+iSCfEIFLBL2IdfToxXZFsdP/oY0dEIhrwwWwqqnQFdZwWMVKaWtBGNNe07+cyCKe2QxcIU6u3X+ZNawEdDbjUly8VR/ISSXnc+Ty1qTVBokXVX8uhuB4Pzr1/Yo+74kEX8I/YTwWhqcwMxXJSssk4lwqelrdWveOiN38jlgk3xUes3lSBYwyn7MY34HQokaJK2Vzk6NiOwIqs42lNgz6HKt8tRGMldsTxUqqARUgYCF2Y1SD1PNeAjLlugkbLi6hgt4zOUHof+9dcz5iVCOfe/mFs+Bye4eL8OXued/NedNtxuteOVjUdv56YK7AZwepvuoFiY4qYjIdDC+r2dnS9jf3FDq3JdvZHhlGxtAGYGynPsqBJAt7O0ghDUyctS4yL/IIcOMNSwCla1hs375LWpw/Qehcd27RCtW9qhEcLCOqOkzzP2LxEZlqvGy+X8cY0Rm/KLpWLcv95r9FeoZJEoLd+9JLniE3zBlkUe6TZR6rEPh8HOoTCvF0MFgvspTPRcNh6OdlEC06ZGFXPTuVK4Wm664sJfyfhmsApPq3pIYSKwx6GcB6udLYjJk0mgDoYVg4+VFrFS4L4bFjvTVhLMsufrp8ysLKJdhLa1iaN4mTePLmivvEh384wsYn9wmKT7Lf0fMcTvGBtMIyhRJzA8v29v90KLxk/4D+vfuhJhFiHaGcjZ//5GPvdq2mKAkg+Kvgv1q4lSRyx0Jaykw7pZD/bdJyZ/n7mpqEY5JewOr2r13nn5hZcQII=
  template:
    metadata:
      creationTimestamp: null
      name: gateway-proxy
      namespace: poketwo
    type: Opaque
