apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: sealed-secrets-controller
    namespace: kube-system
    name: sealed-secrets
    version: 2.6.9
    repo: https://bitnami-labs.github.io/sealed-secrets
