apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poketwo-staging-private

helmCharts:
  - releaseName: mongodb
    namespace: poketwo-staging-private
    name: mongodb
    version: 13.1.1
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml

resources:
  - secret.yaml
