apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: poketwo
spec:
  encryptedData:
    token: AgAm7bpZaU5jxAGYAJjSxhYIk+oZnTMygduZrum0O9iSJR1kB6uUNz2nK3ZlCp6PRsOtjSaAG7QWXCgbRBWGKm6OqQEiXvrnRFL434CrT+XDkQDHIdoPT1ZEmcPzTJWFrAHQjFc/hruE1mYa498pCtShGE2DHiXnAHpbN3CIalx4C3xQJ+AXz4/x7tizgUvLEdDGgi/ONFqVshNrhEfbMwo+sAKoNQL/hrqM0nSBZ/6rZyLmgYm6S+6/T0NP80y5QOaMrmhk+pyGwwVhh9kH/j7jF0UMB/UYz++/lcT8I1MIg/fDZUIT8KgDz/vYs31gQKzrtHc3aSEUS9xfQ6sLKND08XjRpUylsyKWLREhblX0YrUAtmMm7ltFmsWPvzOnDXv46rW++/KMrAaQUlndHvwNHDnl0PtVS61F1rdZQ+ddWspBJK41XSyA+XHkLNe9R8EU5GUtXTAev1bCwzJ7MFlqMbgqXRshJKPA0uzCdzINguPpA4+diBUEFVKM4rqMzw5qz/4UZiBbtvMdM47CZELFsQC8fagBFl82d3kveVX8kPdkFB3hlOH5bTNzWO3GKK4IytbAaEvl2PMJVEd5wghLHDGK4Mw36KUUQCzzbuwfUDkmZD74xcoVzrtWucWCEAcKH+ttFfmZEG45U8gH22IItjTupKUBXBo+0In3gyF5KuC9edz06bLi6JsWTm+CbSjo5OjeoPwy7pkzo5IzoHin49ar4fzQtvEU+vLNb1+P1gNduqZXlPdGZSS+rV56wcaj/nOjNhtILop33xTnznMK/tBRDsKw
  template:
    metadata:
      creationTimestamp: null
      name: poketwo
      namespace: poketwo
    type: Opaque
