apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-server-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: server.poketwo.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-server
                port:
                  number: 8080
