apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: bmt-ag
  namespace: bmt
spec:
  teamId: bmt
  volume:
    size: 8Gi
    storageClass: rook-ceph-block-retain
  numberOfInstances: 2
  users:
    ag:
      - superuser
      - createdb
  databases:
    ag: ag
  postgresql:
    version: "10"
