apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: ag-rabbitmq
  namespace: bmt
spec:
  image: docker.io/bitnami/rabbitmq:3.11.10-debian-11-r5
  replicas: 1
  resources:
    limits:
      memory: 16Gi
    requests:
      memory: 2Gi
