apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slice
subjects:
  - kind: ServiceAccount
    name: slice
    namespace: poketwo-staging
roleRef:
  kind: ClusterRole
  name: slice
  apiGroup: rbac.authorization.k8s.io
