apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slice
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: ["poketwo-0"]
    verbs: ["get", "patch", "delete"]
