apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-system

helmCharts:
  - releaseName: postgres-operator
    namespace: postgres-system
    name: postgres-operator
    version: 1.8.2
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    valuesFile: values.yaml
    includeCRDs: true

  - releaseName: postgres-operator-ui
    namespace: postgres-system
    name: postgres-operator-ui
    version: 1.8.2
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
