apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: oliver@poketwo.net
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: oliver.ni@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-token
              key: api-token
      - http01:
          ingress:
            ingressClassName: nginx
