apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - releaseName: cert-manager
    namespace: cert-manager
    name: cert-manager
    version: 1.12.3
    repo: https://charts.jetstack.io
    includeCRDs: true
