apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBBUAtqWe1gcL0IRrCEhN6SXQKXp2uF10duRm+YcJrxkEGUqgt9d+u4hnt7OGtHabqSC2VjqkRO4K7vnD5I0lZn16bqPJWZFQgbT+xTlVFlUv9WSbtKf/0AA/85PUZJ/1+kTyNhDgB34V7bTtW0lH61hp/qPjfF4ewmD2PWJYPqsEVfX/2sGggZx0FZeY/QJ2P0Z+k3daZVFkTlPUAegjyVbxS9sNGBcQA/KGO1RiNWeTSewPbCIUU6YEn6A4qy78PedynRqeFJ3r/z+MPnD/N/hGiNnYl+7RRpNC6oxG8Y2mKXPgjVdC42ZExkywPa615WhRvgSgvT/mSOyM+NuLBIfXNf7+hZT2jIE71faMuezMSTIGRrKanvgUdIIxZ82YlprUUaLTUkk2JZbN7dF7KTK9JhfRzjRpmcldMFtCke+vmDFh0/BZ8hgTZEFmTg4tcirHIZkIKtwsckxg8OsoHQZPECl4POGK9XUCHGBivXvpi+Bs5J3ywocFlfHjg1YdESd2FQlxKEBzJyFM++Lgxy1vjFm0CUITKkX99hd2t5p+knd4tziVD9wZSyB4cay+1HGT9I/jhENiU756ssqN+y3Fh4FNkb3GJKEozkv1Ug32sMrcnFQwEvtmXkOQSwwwdIhDysAV8GcmZT0o1ZH1+uzogbxQ93n1q3/CMuSZz3oVq1tSoLJ+eWCzopeKBgRP2eIeIsKWcdskeYmXtv024JNfFZgRZmxM/80bgi1gK14JkJeME8/uxd
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
