apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBUQwf6iggifCa+A9K98Us8B6edjx30TgqTkQF8qC2Wr4/r1tzjoNJEOjBZXqoEtauBycqJ+/ai8N4/HfqSRWMEAQCxzpuQWZAAsFJVxcJ5/T6aHdCHmmEP0UnYbCX5G1DO/S+pelc3e1yWuaAxaf3g3P3Y2bedbL5BiHrZUcwtYHYTs6VqqTktZ/ohk/7ZGqSze8ZIjyM7Da/sgQ/Vqf5rSsqLh90v6PbKwEBShJd24Fl816dLtIbkzG0d6WP0p2xtyoRDkAeW1utGZblDhs6XKrETUHMrH0089XDVxIJl/hvDMCVkyFoBzxgcvvyqj/tcPHoPqak6ddKA11UA8wNvAbj1Rm9Y16WptpGgOYi/KCI20KXT1tC6nY4jZXrXRLYpasDTZS85nD0NYzI/O5YPi4YU7j1PjdkaBywSP1KbrjTC9oAT9GVD4PM4A72nUam2e2eiotx//afrOF+sqVgaBQ2RdwB2F/GEM88n4GFq7nmJfRozeore02xXhYzzYPT4/LdfIWUQUwOOALh/1tz8ATtGyl+mPGdS9sWg79RJ5sHAHb2nSoHNLZr3WjYsK9B1TgWKyXr2ycEXlbxQD4SkSXx5qNknRAG7BDnFfgBcAMUfrguE9aTQKyT64S6nLLAHQ0FQ4mv1NqjoQyZo8NPTBr/g3lYJ4ggQthOnn41sD83WJK02qjCOUWAm0OSpyhBg6A3LCNEsUS3to+uW+rsZz0Cz8eyN6/XOOJ8C7ugkvSewRmyQnkEDLWTrhR5p3fcjOMe+19GpkQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
