apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-0
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: datadir-mongodb-0
