architecture: replicaset

auth:
  enabled: true
  existingSecret: mongodb-auth

replicaSetName: poketwo
replicaSetHostnames: true
replicaCount: 2

resources:
  limits:
    cpu: 20000m
    memory: 80Gi
  requests:
    cpu: 6000m
    memory: 60Gi

livenessProbe:
  enabled: false

persistence:
  enabled: true
  size: 3Ti

volumePermissions:
  enabled: true

arbiter:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi

metrics:
  enabled: true

pdb:
  create: true
  minAvailable: 2
