apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-proxy
  namespace: poketwo-staging-private
spec:
  encryptedData:
    config.json: AgBY5dcppAGmIW7HLtdFdhKY4WffyZNn4R3jqwg80e6A4aAojM1SlyOr4AAiSaUXafMvu+Lh1XLukZn2goyBClsMS495R2tqdaLHq6RkI5OmbDJmJwYVAdhEOOIfx2/PE98IMaviXJ4XaQdA84SlE/svgrjXzLGmNz3h0mxkyPxSkBxViU9HfZQG/5q32jJwa9Z3D1kL8mSb5inCGPwm/2wSpacqx51beEy7QE9tVSD27ZuuZdO9ARiUbag8b9fwUgfrdCDW1njxVPVGgSb/iuBvly7X9F3o2pbCjybR6Dgr9NjyZv2PjQObUgmDYGgubPL3YMywZ5SVDGjbJf7deHjdAbj5Q5uki+BSSYXWCcxsP75geeLycAdpvOD8RTq+cmnqRrYLNX+aSQFR4hanWKr/y+U/+Np9DA6BoTIer6XenkaGS/7GZbAsAIJTJfyJTWewkw+iPi4vLBZJLwEVjaIHfxoKlxqSqOMMh3UUT9h7rY3FeemlIlf8VMgSrHmqRX0p6Wg3PusmOJQE8GYwyNDxjjzRYUS1zgOB/lg3qccLUJovdAjtK8tg06upP+sSUjq7pYtZq9FuFegT3u5JtwN5BiyzJGvSDmWqnDPmLo4OZXCxo88hhIgQJ9GPjbAEoDSj4OAKMN1bp39Ps2PRNIcL4zDoMtjnT/AXk7OcH1u5BB0DElY99OtNAKtB9rNntns/XwCbcxAkPWo8kvDeYZesBbJ9umuCrzL8AiOoFCR6ZzIT5Iu3v6Au2/OTB//bPUZQQmeEtbZAl0+vOr38bDBYhWWWitir2mi4m8pucJYy0p2snuJax+OzPvEuQ6ud/si5eYse6sfMqJ4UvZoWlFcSkImPDZDd+IlW6NFTsBOp7Vwz6LzaOTQTaa0ddNVHvEYdcjN5GI4sp/cbejNQKgi348S1xJPyZqCaCJvykjlaMvxABR3aiVm0AFlWCEdetJ2+UoSa8d7Ruzm4TRHjf5YZRPB+TEoHQh/7c/BlRekshdf0i7QHO9qHjEQMpX9LcLTigXEsf9tNeXXT0AUkY8CtP2AH/NY6noyT2ZDxa+OhYJVulDIf8e2IC6v1g5aBXCYKn4HN1E1AJIneBn2LOrUXIsXWF1tKyOj/zqPrFA0K6DXrZ5tE8jDeHwDRRaeapuYQcbZgtVVSPiE6C3k8Gy+gKjMfb4SAIQpc+93Z4CSzDZ2KUXaG5xUbQhBfl4hUFgq9HvAFcm8+7afkIBuu+uGos69EmJbKfEAyhi32EKWPzkhMucJG9BdDpvqJg8wCOz2x+NIK18Indkwl8CmQsC4cTJ6eq4d4F2DlogIvzU9K8ZZPca49nm2Do0LruUCYy7fz93ec52GepFijy4oYcQpkh9XCikzC4//zl41Z
  template:
    metadata:
      creationTimestamp: null
      name: gateway-proxy
      namespace: poketwo-staging-private
    type: Opaque
